# numpy - numerische Berechnungen mit Python
Die Bibliothek numpy erweitert der Funktionsumfang von Python um numerische Berechnungen. Diverse Berechnungen sind zwar bereits auch mit der Grundversion in Python möglich. Jedoch sobald komplexere Aufgaben anstehen, ist man mit dem erheblichen Funktionsumfang in numpy (Listen, Matrizen, Berechnungsfunktionen wie Wurzel ziehen, Logarithmusfunktionen und/oder Matrixfunktionen, etc.) besser und schneller aufgestellt.

In [ ]:
#numpy ist eine Standard-Erweiterung und muss zuvor installiert und gezielt importiert werden. Dafür unter pypi.org das entsprechende Projekt suchen und den den pip install befehl im CMD-Fenster ausführen. In einem Jupyter Notebook muss vor dem pip ein ! stehen, sollte es per Jupyter Notebook installiert werden.
!pip install numpy
#Dieser Befehl muss nur einmal ausgeführt werden. Denn es ist eine Installation. Danach muss nur noch die Bibliothek importiert werden.

In [ ]:
#numpy Bibliothek importieren.
import numpy as np
#numpy wird vollständig importiert und unter dem Kürzel np abufbar gemacht. np tritt daher stets dann auf, wenn auf eine Funktion von numpy zugegriffen wird.
#alternativ kann auch nur eine Funktion aus der Bibliothek herangezogen werden.
#Bsp.
# from numpy import array
nums = [1,2,3,4,5]
print(type(nums))

# Eindimensionales Array erstellen:
b = np.array(nums)

b
print(type(b))

<class 'list'>
<class 'numpy.ndarray'>


## 2.1 numpy Arrays
Ein numpy Array ist im weitesten Sinne eine Liste. Alle Elemente in einem numpy-array sind jedoch vom gleichen Typ und es werden auch keine leeren Objekte gestattet.

In [ ]:
import numpy as np

nums = [1,2,3,4,5]
print(type(nums))

# Eindimensionales Array erstellen:
a = np.array(nums)

a
print(type(a))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
# Zweidimensionale Matrix erstellen
m1 = np.array([ [1,2,3], [4,5,6], [7,8,9] ])

m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Zweidimensionale Matrix erstellen
m2 = np.array([ [1,2,3], [a,b,c], [7,8,9] ])
#Fehlermeldung, da diese Matrix nicht denselben Typ bei allen Elementen hat. Integer und Text-Werte gemischt
m2

NameError: name 'b' is not defined

In [ ]:
#Es können auch Matrizen mit Nullen erstellt werden. So z.B. wenn erst zu einem späteren Zeitpunkt Werte übertragen werden.
m3 = np.zeros( (100,20), int)

m3

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
#mittels arange() und linespace() können in einem vordefinierten Bereich Werte in einer Liste eingetragen werden.
#mittels arange() wird eine Schrittweite vorgegeben
ara = np.arange(0, 5, 0.1,)
print(ara)

#Leerzeile zwecks der Übersichtlichkeit
print("\n")

#mittels linespace() wird die Schrittlänge aufgrund dem Minimal- und dem Maximalwert automatisch ermittelt.
#Syntax hierzu linespace(start, stop, num)
lin = np.linspace(0, 5, 10, endpoint=True)
print(lin)

#Leerzeile zwecks der Übersichtlichkeit
print("\n")

#endpoint true = Der Endpunkt muss dem Stop entsprechen. Endpoint false= Der Endpunkt muss nicht dem Stop entsprechen
lin2 = np.linspace(0, 5, 10, endpoint=False)
print(lin2)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9]


[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


## 2.2 Inhalte in Arrays abrufen und anpassen
Ähnlich einer Liste kann auch auf Elemente in Arrays zugegriffen werden.

In [ ]:
nums = [1,2,3,4,5]

mein_array = np.array(nums)

#Abrufen der Elemente beginnend beim Zählerplatz 0
print(mein_array[1])
#Abrufen des letzten Wertes der Liste (mit - kann die Liste von hinten angelesen werden)
print(mein_array[-1])

#Alle Werte zwischen i >= 0 und i < len(array) sind möglich. Die Indizierung beginnt, wie oben dargestellt bei 0

2
5


In [ ]:
neues_array = np.arange(100)
#print(neues_array)
#Ähnlich dem Slicing in Listen und Tupeln kann auch hier ein Ausschnitt an Elementen herausgezogen werden und bei Bedarf an eine neue Variable übertragen werden.
# Wie bei Listen und Tupeln oder in Excel ;-)  kann ein Intervall selektiert werden.
#print(neues_array[3:8])

# Neben der Selektion kann auch wieder eine Schrittfolge (hier mit der Schrittfolge 2 gezeigt) eingestellt werden.
print(neues_array[3:80:2])
# Ergebnis: array([3, 5, 7])

[ 3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49
 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79]


In [ ]:
#Üblich ist beim Slicing, dass die untere Grenze miteingeschlossen wird. Mittels start:stop:step wird der Bereich festgelegt.
#Sollte start oder step fehlen, so wird der ganze Bereich gewählt.
print(neues_array[60:3:-3])

[60 57 54 51 48 45 42 39 36 33 30 27 24 21 18 15 12  9  6]


In [ ]:
m4 = np.array([ [1,2,3], [4,5,6] ])

print(m4)


# Es soll nur das Element aus der ersten Zeile und der zweiten Spalte ausgegeben werden.
print("Das Element in der ersten Zeile und zweiten Spalte lautet: ",m4[0][1])
# Alternative Schreibeweise für ein Matrix-Slicing
print("Das Element in der ersten Zeile und zweiten Spalte lautet: ",m4[0,1])

## 2.3 Funktionen in numpy
numpy hat sehr viele Funktionen, welche auch im math-Modul bereits existieren. Der Vorteil dieser Funktionen ist jedoch, dass diese Funktionen direkt auf numpy-Arrays anwendbar sind. Hier eine kleine Auswahl an Funktionen. Für mehr am Besten die Entwicklungsseite besuchen: https://numpy.org/doc/stable/reference/index.html

In [ ]:
# neben den üblichen mathematischen Operatoren können z.B. folgende Funktionen angewendet werden. Dabei wird stets ein neues array erstellt. Das Ur-Array bleibt davon unberührt.
op_array = np.arange(10)

print("Originalliste: ",op_array)


print("Originallistenelemente+1: ",op_array+1)


print("Originallistenelemente zum Quadrat: ",op_array**2)


print("Wurzel aus den Elementen in der Originalliste: ",np.sqrt(op_array**4))


print("Sinus aus den Elementen der Originalliste: ",np.sin(op_array))


print("Sigmoid aus den Elementen der Originalliste: ",1/(1 + np.exp(-op_array)))

Originalliste:  [0 1 2 3 4 5 6 7 8 9]
Originallistenelemente+1:  [ 1  2  3  4  5  6  7  8  9 10]
Originallistenelemente zum Quadrat:  [ 0  1  4  9 16 25 36 49 64 81]
Wurzel aus den Elementen in der Originalliste:  [ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]
Sinus aus den Elementen der Originalliste:  [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
Sigmoid aus den Elementen der Originalliste:  [0.5        0.73105858 0.88079708 0.95257413 0.98201379 0.99330715
 0.99752738 0.99908895 0.99966465 0.99987661]


In [ ]:
# Eine weitere interessante Funktion ist das Suchen nach dem geringsten oder größten Wert in einer Liste/Matrix. Dafür wird der Befehl argmin() respektive argmax() genutzt.
mini_liste = np.array( [10,1,2,4,5,2] )
mini_matrix = np.array([ [12013,20,1201], [146,1,23] ])

print(mini_liste)
print(mini_matrix)

print(np.argmin(mini_liste))

print(np.argmin(mini_matrix))

#Mittels dem Argument axis=0 wird eine spaltenweise und mit axis=1 eine zeilenweise Auswertung durchgeführt.
print(np.argmin(mini_matrix, axis=0))

print(np.argmin(mini_matrix, axis=1))

[10  1  2  4  5  2]
[[12013    20  1201]
 [  146     1    23]]
1
4
[1 1 1]
[1 1]
