# 1. Übungen zu Python3 - Allgemeiner Teil
In diesem allgemeinen Teil stehen Übungsaufgaben zu Python3. Also zu den Inhalten aus "1. Programmieren in Python3 -Grundlagen".
- (mathematische und Vergleichs-)Operatoren
- Variablen
- Listen, Tupeln, Dictionaries
- Kontrollstrukturen
- Funktionen
- Objekte und Klassen

In der Folge wird die Aufgabe erwähnt. Schreiben Sie Ihre Lösung als neue Zelle darunter.

## 1.1 Berechnungen
1. Erstellen Sie eine Berechnung einer Variable wie folgt: a ist 2 und soll quadriert werden
2. Das Ergebnis aus a und b =3 sollen in c per Modulo berechnet werden

In [ ]:
# Aufgabe 1.1 1 Berechnung Variable a
a=2**2
print(a)
b=3
c=a%b
print(c)

4
1


## 1.2 Listen...
1. Eine Liste mit dem Namen meine_charts beinhaltet die Werte 3,4,5,2,3 in genau dieser Reihenfolge. Fügen Sie den Wert 10 am Ende hinzu
2. Geben Sie den dritten Wert der Liste aus 1. aus
3. Geben Sie den Typ der obigen Liste aus
4. Überführen Sie die Liste in eine Tupel
5. Überführen Sie die obige Liste bis auf den 4. Wert alles in eine neue Liste mit dem Namen neue_liste
6. Erstellen Sie nun ein Dictionary mit den folgenden Werten: (Student und Note) Peter=3, Mark=2, Hannah=1, Markus=3
7. Fügen Sie einen weiteren Studierenden hinzu: Marta=2

## 1.3 Kontrollstrukturen und Funktionen
1. Hundejahre: Erstellen Sie eine Funktion mit dem Namen Hundejahre und berechnen Sie die Eingabe (Menschenjahre) zu Hundejahren. Die Umrechnung sieht dabei wie folgt aus. Mensch 0-10 Jahre = Hund, Faktor 1,5 - Mensch >10 - 30 Jahre = Hund Faktor 1,6 - Mensch >30 = Hund Faktor 2. Geben Sie den Hundejahrenwert aber auch den Menschenjahrenwert in einem Printbefehl aus.
2. BMI: Erstellen Sie eine Funktion mit dem Namen BMI und geben nach einer Eingabe den Body-Mass-Index zurück. Die Ausgangstabelle für die Berechnung sieht wie folgt aus. Untergewicht wenn der BMI bei Frauen unter 19 und bei Männern unter 20 ist. Normalgewicht, wenn bei Frauen zwischen 19-24 und bei Männern zwischen 20-25 ist. Übergewicht wenn bei Frauen zwischen 25-30 und bei Männern zwischen 26-30 ist. behandlungsbedürftiges Übergewicht, wenn bei Frauen >30 und bei Männern ebenfalls >30. Die Formel für den BMI lautet: BMI=Gewicht*10.000/Größe^2. Welche Werte müssen zuvor abgefragt werden, damit eine Berechnung funktioniert? Führen Sie diese Berechnung aus.
3. Stromkostenrechnung: Sie haben drei Tarife zur Auswahl. Ihr Programm soll den günstigsten Tarif dem Anwender zurückgeben. Der Anwender gibt dafür seinen Jahresstromverbrauch in kWh ein. Tarif 1: Arbeitspreis 15,45 Cent/kWh und Grundpreis 2,97 €/Monat. Tarif 2: Arbeitspreis 13,79 Cent/kWh und Grundpreis 5,94 €/Monat. Tarif 3: Arbeitspreis 11,63 Cent/kWh und Grundpreis 11,84 €/Monat.

In [ ]:
#Aufgabe 1: Hundejahre

In [ ]:
#Aufgabe 2: BMI

In [ ]:
#Aufgabe 3: Stromkostenrechnung
# Eingabewert des Jahresstromverbrauchs in kWh
verbrauch = float(input("Bitte geben Sie Ihren Jahresstromverbrauch in kWh ein: "))

# Berechnung der Stromkosten für jeden Tarif
tarif1 = 15.45 * verbrauch / 100 + 2.97 * 12
tarif2 = 13.79 * verbrauch / 100 + 5.94 * 12
tarif3 = 11.63 * verbrauch / 100 + 11.84 * 12

# Vergleich der Stromkosten und Ausgabe des günstigsten Tarifs
if tarif1 < tarif2 and tarif1 < tarif3:
    print("Der günstigste Tarif ist Tarif 1 mit Kosten von", tarif1, "€/Jahr.")
elif tarif2 < tarif1 and tarif2 < tarif3:
    print("Der günstigste Tarif ist Tarif 2 mit Kosten von", tarif2, "€/Jahr.")
else:
    print("Der günstigste Tarif ist Tarif 3 mit Kosten von", tarif3, "€/Jahr.")

Bitte geben Sie Ihren Jahresstromverbrauch in kWh ein: 20
Der günstigste Tarif ist Tarif 1 mit Kosten von 38.730000000000004 €/Jahr.


## 1.4 Objekte und Klassen
1. Sie haben eine Klasse für ein neuronales Netz. Dieses neuronale Netz soll dabei folgende Parameter variabel übernehmen.
 - Anzahl Schichten
 - Anzahl Neuronen je Schicht
 - Aktivierungsfunktion (hier entweder tanh, sigmoid oder relu) aller Schichten
 - Die Anzahl Schichten sollte >=2 sein
 - Die Anzahl Neuronen sollte >=2 sein
 - Eine Aktivierungsfunktion muss übergeben werden, wenn nicht wird sigmoid gewählt.
 - Geben Sie am Ende die Zusammenfassung Ihres Netzes wieder.

# 2. Übungen zu numpy

In [ ]:
import numpy as np

1. Erstellen Sie einen zweidimensionalen numpy-Array mit folgenden Werten: [1,2,3], [4,5,6], [7,8,9]
2. Überführen Sie die zweite Spalte in einen neuen Array
3. Rufen Sie die letzten zwei Elemente ab und übergeben diese je an eine Variable
4. Lassen Sie alle Werte innerhalb der Matrix aus 1. mit der Exponential-Funktion in somit neue Werte umrechnen und geben diese Matrix aus

5. Erstellen Sie eine 6X6 Nullmatrix und befüllen diese im Anschluss wie folgt:
 - Erste Zeile immer die 1 eintragen
 - Zweite Zeile immer die 2 eintragen usw.

In [ ]:
b = np.zeros([6,6])
print(b)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
# Idee für eine Lösung
b[0:6] = range(1,7)
print(b)

[[1. 2. 3. 4. 5. 6.]
 [1. 2. 3. 4. 5. 6.]
 [1. 2. 3. 4. 5. 6.]
 [1. 2. 3. 4. 5. 6.]
 [1. 2. 3. 4. 5. 6.]
 [1. 2. 3. 4. 5. 6.]]


In [ ]:
# weitere Idee für eine Lösung
b[0:5] = 1
b[1:5] = 2
b[2:5] = 3
b[3:5] = 4
b[4:5] = 5
b[5] = 6
print(b)

[[1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6. 6.]]


In [ ]:
# und noch eine weitere Idee für eine Lösung
i=0
m=0
z=1
while (m <= 6):
  for i in range(6):
    b[m:i]=z
    i= i+1
  i= 0
  m= m+1
  z= z+1
print(b)

[[1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6. 6.]]


In [ ]:
zeilendimension=int(input("Wie viele Zeilen soll die Matrix enthalten?"))
spaltendimension=zeilendimension
b = np.zeros([zeilendimension,spaltendimension])

#
#
####################################
# WICHTIG BEI ALLEN ÜBUNGEN!!!!
# 1. erstmal an das Gesamtproblem herantasten und jeweils prüfen.
# 2. Im zweiten Schritt dann eruieren wie es vereinfacht möglich wäre.
# 3. Und dann erst umsetzen
####################################
#
#

# 1. Herantasten und prüfen
#zaehler=4
#b[0:1]=1
#b[1:2]=2
#b[2:3]=3

# 2. Erkennen ob es Wiederholungen gibt und/oder Werte variabel gestaltet werden können
#b[zaehler-1:zaehler]=zaehler

# 3. Umsetzen
for i in range(zeilendimension+1):
    b[i-1:i]=i

# Lösung ausgeben
print(b)

2
[[1. 1.]
 [2. 2.]]


# 3. Übungen zu pandas

## 3.1 Pfade
1. Öffnen Sie die CSV-Datei country aus dem Ordner DataScienceEssentials\Python3Notebooks\datasets und speichern diese Datei als Dataframe mit dem Namen df_country (HINWEIS: Sollten Sie diese Datei nicht haben, laden Sie diese bitte herunter und legen diese in dem oben genannten Ordner ab)
2. Öfnnen Sie nun die Datei heart.csv aus dem Ordner DataScienceEssentials\Python3Notebooks\2 MachineLearning mit Python3\data und speichern diese Datei als Dataframe df_heart ab.
3. Öfnen Sie nun die Datei Golf_Datensatz_VL.csv aus dem Ordner DataScienceEssentials\Datasets und speichern diese als df_golf ab.
3. Öfnen Sie nun die Datei iris_full.csv aus dem Ordner DataScienceEssentials\Datasets und speichern diese als df_iris ab.

Geben Sie jeweils den Kopf des Dataframe aus.

HINWEIS: Achten Sie auf die Trenner und sonstige Zeichen in den Dateien. D.h. am Besten vorab mit einem Texteditor anschauen und den delimiter festlegen.

## 3.2 Daten rund um einen Dataframe
1. Geben Sie die länge eines dataframe aus.
2. Geben Sie statistische Merkmale des Dataframe heart aus.
3. Geben Sie den Typ des Dataframe aus.
4. Überführen Sie einen Numpy-Nullarray mit 6*4 in ein Pandas Dataframe und zurück

## 3.3 Slicing, Filtern und Sortieren
1. Geben Sie die 3 Zeile des dataframe heart in eine Serie aus
2. Geben Sie die Spalte output aus dem dataframe heart als y aus und den Rest als X und lassen Sie sich diese Vektoren und Matrizen anzeigen.
3. Übergeben Sie aus dem Dataframe country nur die Werte der United States...
4. Sortieren Sie den Dataframe iris nach sepal length.

## 3.4 Pandas GUI
1. Lassen Sie sich einen Dataframe Ihrer Wahl mit Pandas GUI anzeigen und spielen mit den Diagrammen.
2. Können Daten in dieser Tabelle verändert werden, so dass diese dann auch im Dataframe geändert sind?

# 4. Übungen zu Matplotlib und seaborn

HINWEIS: Beachten Sie, dass Sie für die folgenden Grafiken auch die bis hierhin bekannten Module (numpy, pandas) einsetzen sollten.

## 4.1 Matplotlib

1. Nehmen Sie folgende Werte und überführen diese in einen numpy-array --> x= [1,2,3] und y = [4,5,6]
2. Plotten Sie nun ein Liniendiagramm aus dem array in 1.
3. Plotten Sie nun ein Balkendiagramm aus dem array in 1.
4. Fügen Sie dem Liniendiagramm in 2. eine Diagrammtitel, X-Label und Y-Label sowie eine passende Legende hinzu.
5. Fügen Sie nun passende Titel für die Säulen hinzu. Erster Wert=Bananen, Zweiter Wert=Zwiebeln, Dritter Wert=Knoblauch
6. Plotten Sie nun die Werte in 1. in einem Punktdiagramm
7. Stellen Sie nun die drei Diagramme in 4., 5. und 6. nebeneinander auf.

## 4.2 Seaborn

1. Nehmen Sie den Dataframe country aus 3. und visualisieren Sie die populationsentwicklung von China und Indien im Vergleich
2. Berechnen Sie nun ausgehend vom ersten gemessenen Jahr die prozentuale Entwicklung und zeigen diese in einem Liniendiagramm für Indien und China auf.
3. Beziehen Sie den Datensatz titanic aus seaborn (sns.load_dataset("titanic") und überführen diesen in einen pandas-dataframe.
4. Erstellen Sie basierend auf dem titanic-Datensatz einen Violinplot in dem auf der X-Achse die Klassen (Crew, First, Second, Third) aufgezeigt werden. Innerhalb des Violinplots soll nach Geschlecht aufgebaucht(getrennt) werden.
5. Nehmen Sie den heart.csv-Datensatz (lokal auf Ihrem PC) und überführen diesen ebenfalls in einen Dataframe.
6. Erstellen Sie einen Multiscatterplot aus diesem Datensatz in dem der Output farblich dargestellt wird. Als Zwischenplot soll ein Histogramm des Merkmals gezeigt werden.

# 5. Übungen zu Data Science mit SciKit-Learn

HINWEIS: Für die folgende Aufgaben benötigen Sie alle bekannten Bibliotheken und Aspekte, welche Sie bis hierhin gelernt haben. Sie benötigen darüberhinaus diverse Programmschnipsel aus den Dateien:
- 0.0 Vollständiges Beispiel für eine Klassifikation mit Preprocessing
- 0.2 Einfache lineare Regression
- 0.1 Einfache Klassifikation IRIS-Datensatz
- 2.0 Vorverarbeitung für eine Klassifikation oder Regression
- u.w.

## 5.1 Klassifikation ohne Preprocessing
1. Beziehen Sie den iris-Datensatz und überführen diesen in ein Pandas-Dataframe.
2. Überführen Sie die Klassen der drei Blumensorten in die Werte 0, 1 und 2
3. Splitten Sie den Datensatz auf in Training und Test. Testgröße 0.1
4. Nutzen Sie ein neuronales Netz als Model mit der aktivierungsfunktion relu, dem solver adam und einem Hidden Layer Größe von 5,3
5. Geben Sie die Loss-Werte je Iteration aus
6. Plotten Sie die Losskurve
6. Geben Sie auch eine Confusion Matrix aus

## 5.2 Klassifikation mit Preprocessing
1. Beziehen Sie den Iris-Dirty-Datensatz und überführen Sie diesen in einen Pandas-Dataframe.
2. Ermitteln Sie fehlende Werte und eliminieren Sie diese Instanzen
3. Finden Sie Dubletten und löschen auch diese Instanzen
4. Sind Tippfehler oder Zeichendreher in den Klassen zu sehen. Dann diese anpassen
5. Passen Sie die Einheiten an. Es sollten nur Zahlen drin sein. Achten Sie auf Kommatas und Punktierungen bzw. Einheiten bei den Werten.
6. Ermitteln Sie Ausreißer mittels describe und entsprechenden Plots.
7. Ermitteln Sie mittels Pearson Correlation ob Merkmale mit Werten >0,9 korrelieren. Wenn ja lassen Sie diese Merkmale aussen vor.
8. Normalisieren Sie die Daten im Rahmen zwischen 0 und 1
9. Splitten Sie den Datensatz auf in Training und Test. Testgröße 0.1
10. Führen Sie ein oversampling und ein undersampling (Balancing) durch. Nutzen Sie später beide Datensätze (oversampling = 1 und undersampling = 2) bei einer getrennten Modellierung durch. Das bessere Modell wird verwendet.
11. Trainieren Sie einen Nearest Neighbor
12. Plotten Sie die roc-Kurve und die Precision-Recall-Kurve nebeneinander für das oversampling- und das undersampling-Modell.
13. Entscheiden Sie, welches Modell Sie eher für eine Klassifikation verwenden würden.

## 5.3 Regression mit/ohne Preprocessing
1. Beziehen Sie den Datensatz Boston House Pricing aus dem seaborn-Datensatz
2. Führen Sie die Schritte 2 bis 10 aus 5.2 sofern nötig durch
3. Trainieren Sie eine lineare Regression
4. Geben Sie den r2_score je Iteration aus
4. Plotten Sie die Ergebnisse

